package prabin.timsina.documentscanner.ui.opencv

enum class ScanHint {
    ADJUST_ANGLE,
    AREAL_BELOW_LIMITS_AND_EDGE_TOUCHING,
    AREA_ABOVE_LIMITS,
    AREA_BELOW_LIMITS,
    AREA_BEYOND_LIMITS,
    CAPTURING_IMAGE,
    EDGE_TOUCHING,
    HEIGHT_ABOVE_LIMIT,
    WIDTH_ABOVE_LIMIT,
}
